### ISSUE TITLE
[Bug] github SEO WorkFlow Build Error

### ISSUE THREAD

**Issue by Jackchen0514** [openRin/Rin#275]
**Bug 描述**
Blocked 10 postinstalls. Run `bun pm untrusted` for details.
260 |             if (this.puppeteer.configuration.browserRevision) {
261 |                 throw new Error(`Tried to find the browser at the configured path (${executablePath}) for revision ${this.puppeteer.browserRevision}, but no executable was found.`);
262 |             }
263 |             switch (this.product) {
264 |                 case 'chrome':
265 |                     throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                                ^
error: Could not find Chrome (ver. 127.0.6[53](https://github.com/Jackchen0514/Rin/actions/runs/11342035861/job/31596764836#step:6:54)3.88). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /home/runner/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
      at resolveExecutablePath (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:265:27)
      at /home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:83:37

**Comment by OXeu** [comment]
SEO 可以暂时禁用了，目前其实际作用并不大

**Comment by iam2r** [comment]
> **Bug 描述** Blocked 10 postinstalls. Run `bun pm untrusted` for details. 260 | if (this.puppeteer.configuration.browserRevision) { 261 | throw new Error(`Tried to find the browser at the configured path (${executablePath}) for revision ${this.puppeteer.browserRevision}, but no executable was found.`); 262 | } 263 | switch (this.product) { 264 | case 'chrome': 265 | throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` + ^ error: Could not find Chrome (ver. 127.0.6[53](https://github.com/Jackchen0514/Rin/actions/runs/11342035861/job/31596764836#step:6:54)3.88). This can occur if either
> 
> 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
> 2. your cache path is incorrectly configured (which is: /home/runner/.cache/puppeteer).
>    For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
>    at resolveExecutablePath (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:265:27)
>    at /home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:83:37

Set up Puppeteer中的
npx puppeteer browsers install chrome
放到Run script中

    run: |
      cd Rin/
      bun install --frozen-lockfile
      npx puppeteer browsers install chrome
      bun scripts/render.ts
